nelmio_api_doc:
    documentation:
        info:
            title: LeBonCode API
            description: LeBonCode API
            version: 1.0.0
    areas:
        path_patterns:
            - ^/(?!docs(|.json)$|_.*$)
