parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    NicolasLefevre\LeBonCode\Core\Features\Context\:
        resource: '%kernel.app_dir%/Core/Features/Context/'
    NicolasLefevre\LeBonCode\User\Features\RegisterUser\RegisterUserContext: ~
    NicolasLefevre\LeBonCode\User\Features\AuthenticateUser\AuthenticateUserContext: ~
    NicolasLefevre\LeBonCode\Advert\Features\CreateAdvert\CreateAdvertContext: ~
    NicolasLefevre\LeBonCode\Advert\Features\GetAdvert\GetAdvertContext: ~
