app.swagger:
    path: /docs.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app.swagger_ui:
    path: /docs
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
