name: CI

on:
  pull_request:
    types: [ opened, synchronize, reopened, labeled ]
  push:
    branches: [ main ]

jobs:
  QA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: make build

      - name: Install dependencies
        run: make vendor

      - name: Run Deptrac
        run: make deptrac

      - name: Run PHPStan
        run: make phpstan

      - name: Run Rector
        run: make rector-ci

      - name: Run PHP-CS-Fixer
        run: make php-cs-fixer

  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: make build

      - name: Start Docker
        run: make start

      - name: Install dependencies
        run: make vendor

      - name: Run unit tests
        run: make unit-tests

      - name: Start database
        run: make db-reset-test

      - name: Run integration tests
        run: make int-tests

      - name: Start server
        run: make start

      - name: Run e2e tests
        run: make e2e-progress

      - name: Run security checker
        run: make security
